export interface ConstitutionAreaDefinition {
  id: number;
  title: string;
}

export const CONSTITUTION_AREA_DEFINITIONS: ConstitutionAreaDefinition[] = [
  { id: 1, title: "Repository layout" },
  { id: 2, title: "Monorepo / single-project model" },
  { id: 3, title: "Source directory organization" },
  { id: 4, title: "Test directory organization" },
  { id: 5, title: "Documentation organization" },
  { id: 6, title: "Script/tool directory organization" },
  { id: 7, title: "Generated/build directory handling" },
  { id: 8, title: "Asset/static file organization" },
  { id: 9, title: "Package/dependency manager" },
  { id: 10, title: "Manifest files" },
  { id: 11, title: "Lockfile strategy" },
  { id: 12, title: "Dependency version policy" },
  { id: 13, title: "Private registry/package source usage" },
  { id: 14, title: "Dependency vulnerability/licensing controls" },
  { id: 15, title: "Environment separation" },
  { id: 16, title: "Environment variable conventions" },
  { id: 17, title: "Secrets handling" },
  { id: 18, title: "Configuration hierarchy" },
  { id: 19, title: "Runtime/language version pinning" },
  { id: 20, title: "Local development bootstrap" },
  { id: 21, title: "Containerized development/runtime configuration" },
  { id: 22, title: "File naming conventions" },
  { id: 23, title: "Type/class/component naming" },
  { id: 24, title: "Variable/function naming" },
  { id: 25, title: "Constant naming" },
  { id: 26, title: "Import/export conventions" },
  { id: 27, title: "In-file organization" },
  { id: 28, title: "File size conventions" },
  { id: 29, title: "Function/method size conventions" },
  { id: 30, title: "Comment/documentation conventions" },
  { id: 31, title: "TODO/FIXME/HACK conventions" },
  { id: 32, title: "Overall application architecture" },
  { id: 33, title: "Module/package boundaries" },
  { id: 34, title: "Layering/dependency direction" },
  { id: 35, title: "Feature/domain organization" },
  { id: 36, title: "Shared/common code strategy" },
  { id: 37, title: "Dependency injection/inversion approach" },
  { id: 38, title: "Cross-module communication rules" },
  { id: 39, title: "Architectural boundary enforcement" },
  { id: 40, title: "API style/protocols" },
  { id: 41, title: "Route/endpoint organization" },
  { id: 42, title: "API versioning" },
  { id: 43, title: "Request validation" },
  { id: 44, title: "Response contracts" },
  { id: 45, title: "Error response format" },
  { id: 46, title: "Pagination/filtering conventions" },
  { id: 47, title: "Idempotency/rate-limit contract handling" },
  { id: 48, title: "Database/storage technologies" },
  { id: 49, title: "ORM/query/data-access approach" },
  { id: 50, title: "Model/schema organization" },
  { id: 51, title: "Migration strategy" },
  { id: 52, title: "Transaction boundaries" },
  { id: 53, title: "Query performance conventions" },
  { id: 54, title: "Indexing/data access conventions" },
  { id: 55, title: "Seed/fixture/reference-data handling" },
  { id: 56, title: "Error handling conventions" },
  { id: 57, title: "Timeout conventions" },
  { id: 58, title: "Retry/backoff policy" },
  { id: 59, title: "Circuit-breaking/failure isolation" },
  { id: 60, title: "Graceful degradation/fallbacks" },
  { id: 61, title: "Health/readiness/liveness checks" },
  { id: 62, title: "Idempotent operation handling" },
  { id: 63, title: "Authentication approach" },
  { id: 64, title: "Authorization/permission model" },
  { id: 65, title: "Input validation/sanitization" },
  { id: 66, title: "Output encoding/XSS controls" },
  { id: 67, title: "CSRF/CORS/browser security controls" },
  { id: 68, title: "Secrets scanning/storage" },
  { id: 69, title: "Dependency/SCA security scanning" },
  { id: 70, title: "Static code/security analysis" },
  { id: 71, title: "Encryption/TLS/data protection" },
  { id: 72, title: "Security headers/network trust boundaries" },
  { id: 73, title: "Test framework/tooling" },
  { id: 74, title: "Unit test conventions" },
  { id: 75, title: "Integration test conventions" },
  { id: 76, title: "End-to-end test conventions" },
  { id: 77, title: "Test naming/location conventions" },
  { id: 78, title: "Mock/fake/test-double strategy" },
  { id: 79, title: "Test data/factory/fixture strategy" },
  { id: 80, title: "Coverage/flaky-test/quality gates" },
  { id: 81, title: "Build commands/tooling" },
  { id: 82, title: "Development/start commands" },
  { id: 83, title: "Linting rules/tooling" },
  { id: 84, title: "Formatting rules/tooling" },
  { id: 85, title: "Type checking/static analysis" },
  { id: 86, title: "Repository automation scripts" },
  { id: 87, title: "CI/CD platform" },
  { id: 88, title: "Pipeline stages" },
  { id: 89, title: "Branch/PR pipeline triggers" },
  { id: 90, title: "Required quality checks" },
  { id: 91, title: "Build artifact creation/retention" },
  { id: 92, title: "Pipeline dependency/build caching" },
  { id: 93, title: "Deployment automation" },
  { id: 94, title: "Logging format/conventions" },
  { id: 95, title: "Log levels and production logging" },
  { id: 96, title: "Request/trace/correlation IDs" },
  { id: 97, title: "Metrics instrumentation" },
  { id: 98, title: "Distributed tracing" },
  { id: 99, title: "Alerting/operational monitoring" },
  { id: 100, title: "Caching strategy" },
  { id: 101, title: "Async/background work" },
  { id: 102, title: "Payload/upload size controls" },
  { id: 103, title: "Connection/resource pooling" },
  { id: 104, title: "Performance profiling/benchmarking" },
  { id: 105, title: "Scalability/concurrency conventions" },
  { id: 106, title: "Branch naming/workflow" },
  { id: 107, title: "Commit message conventions" },
  { id: 108, title: "Pull request conventions" },
  { id: 109, title: "Review/approval requirements" },
  { id: 110, title: "Protected branch/force-push rules" },
  { id: 111, title: "Code ownership rules" },
  { id: 112, title: "Deployment model" },
  { id: 113, title: "Environment promotion strategy" },
  { id: 114, title: "Versioning/release strategy" },
  { id: 115, title: "Feature flag/release-control strategy" },
  { id: 116, title: "Rollback/recovery strategy" },
  { id: 117, title: "Sensitive/PII data handling" },
  { id: 118, title: "Audit/retention/access logging controls" },
  { id: 119, title: "Complexity/duplication/technical-debt controls" },
  { id: 120, title: "Simplicity/reuse/anti-overengineering conventions" },
];
