import type { ConstitutionArea } from "../types.js";
import type { ConstitutionEvaluationContext } from "./shared.js";
import { buildRefreshNote, distinctRoots, makeArea } from "./shared.js";

export function evaluateFoundationAreas(context: ConstitutionEvaluationContext): ConstitutionArea[] {
  const { discovery, impactedAreaIds, noChange } = context;

  return [
    makeArea(1, "Repository layout", "DEFINED", `Tracked repository with ${discovery.trackedFiles.length} files and source roots in ${distinctRoots(discovery.sourceFiles).join(", ") || "none"}.${buildRefreshNote(1, impactedAreaIds, noChange)}`, distinctRoots(discovery.sourceFiles).map((root) => ({ kind: "file" as const, path: root, detail: "source root" }))),
    makeArea(2, "Monorepo / single-project model", discovery.trackedFiles.some((file) => file.startsWith("packages/")) ? "INFERRED" : "DEFINED", `${discovery.trackedFiles.some((file) => file.startsWith("packages/")) ? "Repository appears to use a package-based monorepo layout." : "Repository appears to be a single primary project."}${buildRefreshNote(2, impactedAreaIds, noChange)}`, discovery.manifests.map((file) => ({ kind: "file" as const, path: file, detail: "workspace/manifests" })), discovery.trackedFiles.some((file) => file.startsWith("packages/")) ? "HIGH" : undefined),
    makeArea(3, "Source directory organization", discovery.sourceFiles.length > 0 ? "DEFINED" : "NOT_DEFINED", `${distinctRoots(discovery.sourceFiles).length > 0 ? `Detected source roots: ${distinctRoots(discovery.sourceFiles).join(", ")}.` : "No source roots detected."}${buildRefreshNote(3, impactedAreaIds, noChange)}`, distinctRoots(discovery.sourceFiles).map((root) => ({ kind: "file" as const, path: root, detail: "source organization" }))),
    makeArea(4, "Test directory organization", discovery.testFiles.length > 0 ? "INFERRED" : "NOT_DEFINED", `${discovery.testFiles.length > 0 ? `Detected ${discovery.testFiles.length} test files and directories.` : "No test files detected."}${buildRefreshNote(4, impactedAreaIds, noChange)}`, discovery.testFiles.slice(0, 10).map((file) => ({ kind: "file" as const, path: file, detail: "test organization" })), discovery.testFiles.length > 0 ? "HIGH" : undefined),
    makeArea(5, "Documentation organization", discovery.docsFiles.length > 0 ? "DEFINED" : "NOT_DEFINED", `${discovery.docsFiles.length > 0 ? `Detected documentation files in ${distinctRoots(discovery.docsFiles).join(", ")}.` : "No documentation files detected beyond defaults."}${buildRefreshNote(5, impactedAreaIds, noChange)}`, discovery.docsFiles.slice(0, 10).map((file) => ({ kind: "file" as const, path: file, detail: "documentation file" }))),
    makeArea(6, "Script/tool directory organization", discovery.scriptFiles.length > 0 ? "DEFINED" : "NOT_DEFINED", `${discovery.scriptFiles.length > 0 ? `Detected script/tool directories in ${distinctRoots(discovery.scriptFiles).join(", ")}.` : "No dedicated scripts/tools directories detected."}${buildRefreshNote(6, impactedAreaIds, noChange)}`, discovery.scriptFiles.slice(0, 10).map((file) => ({ kind: "file" as const, path: file, detail: "script/tool file" }))),
    makeArea(7, "Generated/build directory handling", discovery.generatedFiles.length > 0 ? "DEFINED" : "NOT_DEFINED", `${discovery.generatedFiles.length > 0 ? `Generated/build outputs are present under ${distinctRoots(discovery.generatedFiles).join(", ")}.` : "No generated/build output handling evidence detected."}${buildRefreshNote(7, impactedAreaIds, noChange)}`, discovery.generatedFiles.slice(0, 10).map((file) => ({ kind: "file" as const, path: file, detail: "generated/build output" }))),
    makeArea(8, "Asset/static file organization", discovery.assetFiles.length > 0 ? "INFERRED" : "NOT_APPLICABLE", `${discovery.assetFiles.length > 0 ? `Detected ${discovery.assetFiles.length} asset/static files.` : "No obvious asset/static file organization detected."}${buildRefreshNote(8, impactedAreaIds, noChange)}`, discovery.assetFiles.slice(0, 10).map((file) => ({ kind: "file" as const, path: file, detail: "asset/static file" })), discovery.assetFiles.length > 0 ? "MEDIUM" : undefined),
    makeArea(9, "Package/dependency manager", discovery.packageManagers.length > 0 ? "DEFINED" : "NOT_DEFINED", `${discovery.packageManagers.length > 0 ? `Detected package managers: ${discovery.packageManagers.join(", ")}.` : "No package manager could be determined."}${buildRefreshNote(9, impactedAreaIds, noChange)}`, [...discovery.manifests, ...discovery.lockfiles].map((file) => ({ kind: "file" as const, path: file, detail: "package manager evidence" }))),
    makeArea(10, "Manifest files", discovery.manifests.length > 0 ? "DEFINED" : "NOT_DEFINED", `${discovery.manifests.length > 0 ? `Detected manifests: ${discovery.manifests.join(", ")}.` : "No manifests detected."}${buildRefreshNote(10, impactedAreaIds, noChange)}`, discovery.manifests.map((file) => ({ kind: "file" as const, path: file, detail: "manifest file" }))),
    makeArea(11, "Lockfile strategy", discovery.lockfiles.length > 0 ? "DEFINED" : "NOT_DEFINED", `${discovery.lockfiles.length > 0 ? `Detected lockfiles: ${discovery.lockfiles.join(", ")}.` : "No lockfiles detected."}${buildRefreshNote(11, impactedAreaIds, noChange)}`, discovery.lockfiles.map((file) => ({ kind: "file" as const, path: file, detail: "lockfile" }))),
    makeArea(15, "Environment separation", discovery.envFiles.length > 0 ? "INFERRED" : "NOT_DEFINED", `${discovery.envFiles.length > 0 ? `Detected environment files: ${discovery.envFiles.join(", ")}.` : "No environment separation files detected."}${buildRefreshNote(15, impactedAreaIds, noChange)}`, discovery.envFiles.map((file) => ({ kind: "file" as const, path: file, detail: "environment file" })), discovery.envFiles.length > 0 ? "MEDIUM" : undefined),
    makeArea(16, "Environment variable conventions", discovery.envFiles.length > 0 ? "INFERRED" : "NOT_DEFINED", `${discovery.envFiles.length > 0 ? "Environment variables appear to be file-driven via .env-style files." : "No environment variable convention evidence detected."}${buildRefreshNote(16, impactedAreaIds, noChange)}`, discovery.envFiles.map((file) => ({ kind: "file" as const, path: file, detail: "environment convention" })), discovery.envFiles.length > 0 ? "MEDIUM" : undefined),
    makeArea(19, "Runtime/language version pinning", discovery.versionFiles.length > 0 ? "DEFINED" : "NOT_DEFINED", `${discovery.versionFiles.length > 0 ? `Detected runtime/version pinning evidence in ${discovery.versionFiles.join(", ")}.` : "No explicit runtime/version pinning detected."}${buildRefreshNote(19, impactedAreaIds, noChange)}`, discovery.versionFiles.map((file) => ({ kind: "file" as const, path: file, detail: "runtime/version file" }))),
    makeArea(20, "Local development bootstrap", Object.keys(discovery.commands).length > 0 ? "DEFINED" : "NOT_DEFINED", `${Object.keys(discovery.commands).length > 0 ? `Repository bootstrap/developer commands are script-driven: ${Object.keys(discovery.commands).join(", ")}.` : "No local bootstrap commands detected."}${buildRefreshNote(20, impactedAreaIds, noChange)}`, Object.entries(discovery.commands).map(([name, value]) => ({ kind: "pattern" as const, detail: `${name}: ${value}` }))),
    makeArea(21, "Containerized development/runtime configuration", discovery.dockerFiles.length > 0 ? "DEFINED" : "NOT_APPLICABLE", `${discovery.dockerFiles.length > 0 ? `Detected container files: ${discovery.dockerFiles.join(", ")}.` : "No containerized runtime configuration detected."}${buildRefreshNote(21, impactedAreaIds, noChange)}`, discovery.dockerFiles.map((file) => ({ kind: "file" as const, path: file, detail: "container file" }))),
  ];
}
