import type { ConstitutionArea } from "../types.js";
import type { ConstitutionEvaluationContext } from "./shared.js";
import { buildRefreshNote, makeArea } from "./shared.js";

export function evaluateToolingAreas(context: ConstitutionEvaluationContext): ConstitutionArea[] {
  const { discovery, impactedAreaIds, noChange } = context;

  return [
    makeArea(73, "Test framework/tooling", discovery.testFiles.length > 0 ? "INFERRED" : "NOT_DEFINED", `${discovery.testFiles.length > 0 ? "Test tooling is implied by test file presence and package scripts." : "No test framework/tooling evidence detected."}${buildRefreshNote(73, impactedAreaIds, noChange)}`, discovery.testFiles.slice(0, 10).map((file) => ({ kind: "file" as const, path: file, detail: "test framework evidence" })), discovery.testFiles.length > 0 ? "MEDIUM" : undefined),
    makeArea(81, "Build commands/tooling", discovery.commands.build ? "DEFINED" : "NOT_DEFINED", `${discovery.commands.build ? `Build command detected: ${discovery.commands.build}.` : "No build command detected."}${buildRefreshNote(81, impactedAreaIds, noChange)}`, discovery.commands.build ? [{ kind: "pattern" as const, detail: `build: ${discovery.commands.build}` }] : []),
    makeArea(83, "Linting rules/tooling", discovery.lintFiles.length > 0 || Boolean(discovery.commands.lint) ? "DEFINED" : "NOT_DEFINED", `${discovery.lintFiles.length > 0 || discovery.commands.lint ? `Linting evidence detected${discovery.commands.lint ? ` with command ${discovery.commands.lint}` : ""}.` : "No linting rules/tooling detected."}${buildRefreshNote(83, impactedAreaIds, noChange)}`, [...discovery.lintFiles.map((file) => ({ kind: "file" as const, path: file, detail: "lint config" })), ...(discovery.commands.lint ? [{ kind: "pattern" as const, detail: `lint: ${discovery.commands.lint}` }] : [])]),
    makeArea(84, "Formatting rules/tooling", discovery.formatFiles.length > 0 ? "DEFINED" : "NOT_DEFINED", `${discovery.formatFiles.length > 0 ? `Formatting configuration detected in ${discovery.formatFiles.join(", ")}.` : "No formatting rules/tooling detected."}${buildRefreshNote(84, impactedAreaIds, noChange)}`, discovery.formatFiles.map((file) => ({ kind: "file" as const, path: file, detail: "format config" }))),
    makeArea(85, "Type checking/static analysis", discovery.typecheckFiles.length > 0 || Boolean(discovery.commands.typecheck) ? "DEFINED" : "NOT_DEFINED", `${discovery.typecheckFiles.length > 0 || discovery.commands.typecheck ? `Type checking/static analysis evidence detected${discovery.commands.typecheck ? ` with command ${discovery.commands.typecheck}` : ""}.` : "No type checking/static analysis detected."}${buildRefreshNote(85, impactedAreaIds, noChange)}`, [...discovery.typecheckFiles.map((file) => ({ kind: "file" as const, path: file, detail: "typecheck config" })), ...(discovery.commands.typecheck ? [{ kind: "pattern" as const, detail: `typecheck: ${discovery.commands.typecheck}` }] : [])]),
    makeArea(87, "CI/CD platform", discovery.ciFiles.length > 0 ? "DEFINED" : "NOT_DEFINED", `${discovery.ciFiles.some((file) => file.startsWith(".github/workflows/")) ? "GitHub Actions appears to be the CI/CD platform." : discovery.ciFiles.length > 0 ? `CI/CD platform files detected: ${discovery.ciFiles.join(", ")}.` : "No CI/CD platform detected."}${buildRefreshNote(87, impactedAreaIds, noChange)}`, discovery.ciFiles.map((file) => ({ kind: "file" as const, path: file, detail: "CI/CD platform file" }))),
  ];
}
